In [2]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward() # 反向传播

In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [8]:
y = x.sum()

In [9]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 非标量变量的反向传播

In [8]:
x.grad.zero_()
y = x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [9]:
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

### 分离计算

In [10]:
x.grad.zero_()
y = x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [12]:
u = y.detach()
u

tensor([0., 1., 4., 9.])

In [13]:
z = u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [15]:
x.grad.zero_()
y = x*x
u = y
z = x*u
z.sum().backward()
x.grad

tensor([ 0.,  3., 12., 27.])