In [4]:
import pandas as pd
import os

In [5]:
data_file = os.path.join('.','data','house_tiny.csv')

In [7]:
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

读入csv的值

In [14]:
inputs , outputs = data.iloc[:,0:2] , data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only=True)) # 仅处理纯数字
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

fillna填充NaN，mean取平均值

In [19]:
inputs = pd.get_dummies(inputs , dummy_na = True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


把alley转化为两列，一列是为NaN一列不为NaN

In [21]:
import torch

X = torch.tensor(inputs.to_numpy(dtype = float))
y = torch.tensor(outputs.to_numpy(dtype = float))
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

转化为tensor

### 下面是额外任务，删除缺失值最多的一列

In [33]:
inputs , outputs = data.iloc[:,0:2] , data.iloc[:,2]
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [34]:
delete_column = inputs.isnull().sum().idxmax() # 直接找到缺失值最多的那一列

In [35]:
inputs = inputs.drop(columns=[delete_column])
inputs

NumRooms
0       NaN
1       2.0
2       4.0
3       NaN

In [41]:
inputs = inputs.fillna(inputs.mean())

In [43]:
X = torch.tensor(inputs.to_numpy(dtype=float))
X

tensor([[3.],
        [2.],
        [4.],
        [3.]], dtype=torch.float64)