In [51]:
import torch

In [52]:
x = torch.arange(12)

In [53]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
x.shape

torch.Size([12])

In [55]:
x.numel()

12

In [56]:
x = x.reshape(2,6)

In [57]:
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

### reshape(2,6) 等同于 reshape(-1,6)，自动计算

In [58]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [59]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [60]:
torch.randn(3,4)

tensor([[ 1.2546,  0.8799, -0.3717,  0.5825],
        [-0.5004, -0.7182, -0.3305, -0.0898],
        [ 1.1926, -0.2552, -1.3295,  1.3353]])

### torch.randn()随机生成一个张量

In [61]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [62]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### torch.exp其实就是计算x中每个元素的e^x

In [63]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.randn(3,4)
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [-0.5649,  1.1084,  0.0291, -0.2098],
         [ 1.8515, -0.4200,  0.1358, -0.7473],
         [ 1.7436,  0.7147, -0.4087,  1.4916]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000, -0.5649,  1.1084,  0.0291, -0.2098],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  1.8515, -0.4200,  0.1358, -0.7473],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  1.7436,  0.7147, -0.4087,  1.4916]]))

### torch.cat拼接张量，dim指定拼接第几维

In [64]:
x < y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [65]:
x.sum()

tensor(66.)

In [66]:
a = torch.arange(3).reshape(3,-1)
b = torch.arange(2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([0, 1]))

In [67]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 广播机制

不同形状的张量直接相加，复制去拓展

In [68]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [69]:
x[0:2,:]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [70]:
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [71]:
before = id(x)
x[:] = torch.zeros_like(x)
before == id(x)

True

In [72]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

多么优秀的转化，伟大无需多言

In [73]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)