  ## 线性代数

### 标量

In [1]:
import torch

In [2]:
x = torch.tensor(2)
y = torch.tensor(3)

x+y,x*y,x/y,x**y

(tensor(5), tensor(6), tensor(0.6667), tensor(8))

### 向量

用一维张量表示向量

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3] #下标形式访问

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

### 矩阵

通过reshape函数生成矩阵

In [8]:
x = torch.arange(20)
x = x.reshape(4,5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [10]:
x[0][1] # 下标取标量

tensor(1)

In [12]:
x.T # 矩阵的转置

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [15]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [17]:
B == B.T # B是对称矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 张量

In [19]:
X = torch.arange(24).reshape(2,3,4) # 三维张量
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [44]:
A = torch.arange(20 , dtype = float).reshape(5,4)
B = A.clone()
A , A+B , A*B , A**2 , A**2 == A*B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]], dtype=torch.float64),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]], dtype=torch.float64),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]], dtype=torch.float64),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [45]:
2 * X # 标量乘张量不改变张量的形状

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [26]:
x = torch.arange(4)
x,x.sum() # sum求和

(tensor([0, 1, 2, 3]), tensor(6))

In [30]:
print(A)
A.shape,A.sum() # 直接sum取总和

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


(torch.Size([5, 4]), tensor(190))

In [37]:
A.sum(axis = 0),A.sum(axis = 1) # 按一个轴求和(降维求和)

(tensor([40, 45, 50, 55]), tensor([ 6, 22, 38, 54, 70]))

In [38]:
A.sum(axis = [0,1])

tensor(190)

In [46]:
A.mean() , A.sum() / A.numel()

(tensor(9.5000, dtype=torch.float64), tensor(9.5000, dtype=torch.float64))

In [47]:
A.mean(axis = 0)

tensor([ 8.,  9., 10., 11.], dtype=torch.float64)

In [49]:
sum_A = A.sum(axis = 1 , keepdims = True) # 不降维按一个轴求和
sum_A , sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]], dtype=torch.float64),
 torch.Size([5, 1]))

In [52]:
A , A / sum_A  # 广播机制，强大

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]], dtype=torch.float64))

In [53]:
A.cumsum(axis = 0) # 求累计总和

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]], dtype=torch.float64)

点积（数量积）

In [56]:
x = torch.arange(4 , dtype = float)
y = torch.ones(4 , dtype = float)
x , y , torch.dot(x,y)

(tensor([0., 1., 2., 3.], dtype=torch.float64),
 tensor([1., 1., 1., 1.], dtype=torch.float64),
 tensor(6., dtype=torch.float64))

In [58]:
(x * y).sum() # 等同于点积

tensor(6., dtype=torch.float64)

In [60]:
A.shape , x.shape , A , x

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([0., 1., 2., 3.], dtype=torch.float64))

In [62]:
torch.mv(A,x) # 按行点乘

tensor([ 14.,  38.,  62.,  86., 110.], dtype=torch.float64)

In [67]:
B = torch.ones(4,3 , dtype = float)
A,B , torch.mm(A,B) # 就是矩阵的乘法

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]], dtype=torch.float64))

In [70]:
u = torch.tensor([3.0 , -4.0])
torch.norm(u) # u的L2范数，就是u的长度

tensor(5.)

In [73]:
torch.abs(u).sum() # u的L1范数 - > 向量元素绝对值之和

tensor(7.)

Frobenius范数就是矩阵中所有元素的平方和的平方根

In [74]:
torch.norm(torch.ones(4,9))

tensor(6.)

In [76]:
### 练习